CREATE DATABASE IF NOT EXISTS mood_db;
USE mood_db;


CREATE TABLE IF NOT EXISTS journals (
id INT AUTO_INCREMENT PRIMARY KEY,
entry TEXT NOT NULL,
mood VARCHAR(50),
score FLOAT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
